language: python
python:
    - 2.7
    - 3.4
compiler:
    - clang
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - python-numpy
        - python3-numpy
before_install:
    - mkdir -p ~/julia
    - curl -s -L --retry 7 https://julialang.s3.amazonaws.com/bin/linux/x64/0.3/julia-0.3.12-linux-x86_64.tar.gz | tar -C ~/julia -x -z --strip-components=1 -f -
    - export PATH="${PATH}:${HOME}/julia/bin"
    - julia -e 'versioninfo()'
script:
    - julia -e 'Pkg.add("PyCall")'
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir())/PyCall`); Pkg.resolve()'
    - julia -e 'using PyCall; @assert isdefined(:PyCall); @assert typeof(PyCall) === Module'
    - python -m unittest discover
