language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
compiler:
  - clang
env:
  matrix:
    - JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies" 
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - sudo apt-get install python-numpy python3-numpy -y
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir())/PyCall`); Pkg.resolve()'
  - julia -e 'using PyCall; @assert isdefined(:PyCall); @assert typeof(PyCall) === Module'
  - python -m unittest test.test_core
